services:
  - type: web
    name: php-node-compiler
    env: php
    buildCommand: ./render-build.sh
    startCommand: node server.js
    envVars:
      - key: PHP_VERSION
        value: "7.4"
      - key: NODE_VERSION
        value: "16"
